[package]
name = "rogue-like"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.7", features = ["dynamic"] }
bevy-inspector-egui = "0.10"
bevy_ecs_tilemap = "0.6.0"
rand = "0.8"
